### ISSUE TITLE
Request for `badges` npm name

### ISSUE THREAD

**Issue by balupton** [boennemann/badges#10]
Hey @boennemann 

I manage the [Bevry Community](http://bevry.me) and we have two projects we'd like to consolidate:

- [Projectz](http://github.com/bevry/projectz) - [badge code](https://github.com/bevry/projectz/blob/master/src/lib/badge-util.coffee)
- [DocPad Plugin Services](http://github.com/docpad/docpad-plugin-services) - [badge code](https://github.com/docpad/docpad-plugin-services/blob/master/src/services.plugin.coffee#L39-L343)

Which both utilise badges to varying degrees. I'd like to consolidate their badge code into a `badges` package, which will contain code used to display every badge there is.

Is it possible to gain access to the `badges` npm name from you to accomplish this? Would really appreciate that.

**Comment by boennemann** [comment]
`badges` is yours to take :)

**Comment by balupton** [comment]
Sweet thanks!

**Comment by balupton** [comment]
Pushing up now.

**Comment by balupton** [comment]
Nope, failed:

```
$ npm publish
npm ERR! publish Failed PUT 403
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/balupton/.nvm/versions/node/v4.0.0/bin/node" "/Users/balupton/.nvm/versions/node/v4.0.0/bin/npm" "publish"
npm ERR! node v4.0.0
npm ERR! npm  v3.3.2
npm ERR! code E403

npm ERR! You do not have permission to publish 'badges'. Are you logged in as the correct user? : badges
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/balupton/Projects/focus/badges/npm-debug.log
```

**Comment by boennemann** [comment]
@balupton sorry for the delay, no idea why it was still published.

```
$ npm unpublish badges --force
npm WARN using --force I sure hope you know what you are doing.
- badges```

**Comment by balupton** [comment]
@boennemann fantastic, great timing. Grabbed: https://www.npmjs.com/package/badges :-)

**Comment by boennemann** [comment]
Awesome, congrats :+1:

**Comment by balupton** [comment]
v1.0.0 now released :)
